language: python
pyhton:
- '3.7'
install:
- pip install -r requirements.txt
script:
- python3 manage.py test
deploy:
  provider: heroku
  app: curs-online-store
  api_key:
    secure: f3buCCkrTLCbdtLdqnSTpd5A08SKtPu8mbi7smLWWy+3sVL3kuaDbxcGWkqc+VnCRtW7vSStRZ4TYLftVMrBnOAYJttjXH53NRdLj2x7SiULlyFF2R1e+/ecBkYprFpZBJg9JzjQPbyjdg/sz+Sna4RsJXQitAGYWFtyGDC0UmrBFz5LtJTPlC40t/T54plhL+rnXe3/q1jsKVPsDts++7K+F7L7LYX2c6kT4EBEwW30VObAOhe6LAA8wJ9M9JNo5Z2yCEVo9Ip1mw1s4k7T1RWkFFFiHdgY9kiLZNYMrYC9udF22of4IftyP3uSGSxNxjg1Erj25s5XfPhmQI+xuZTG0XbMN7/JqqE0s0QkPR0Xyk9cXK531jaJEZw7uw741r7hpGaIYJ4NBYjMpKk2It54TIaPx1gH0ROgV52YxcS1mBIqaCdKPDGzyqqnnNG8vKG8bQci/SwCoKp2x/6VwD+kOFemClKYl9+aTash1t+749SK+txXL1SL7Z5HW8HZ5bgZRa4QkLZ6OG/3PLwYGSSEDx2HHq/eD8C/NdpOs3XbnXf+OQYhO5OeKNQhl7tKWNpknb5xKUT14OjgQ3yx4DhmjUbMz9sXF6q+AF7zpWM13Iy/Ij5TQGPdgRkI+GppsicnhLx1EQWbPqi2LVmBHOLANJPPd0Fh6MQOfT61b6Q=
