# Generated by Django 2.2.4 on 2020-04-20 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('DR', 'Dairy'), ('BK', 'Bakery'), ('FR', 'Fruits'), ('VG', 'Vegetables'), ('BEV', 'Beverages'), ('OTH', 'Other')], default='OTH', max_length=100)),
                ('price', models.FloatField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
