# Generated by Django 2.2.4 on 2020-04-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0002_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items/images/'),
        ),
    ]
