# Generated by Django 3.0.7 on 2020-06-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0003_auto_20200422_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Lipstick', 'Lipstick'), ('Mascara', 'Mascara'), ('Foundation', 'Foundation'), ('Powder', 'Powder'), ('Blush', 'Blush'), ('Eyeliner', 'Eyeliner')], default='Lipstick', max_length=100),
        ),
    ]
