# Generated by Django 2.2.13 on 2020-06-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0004_auto_20200615_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
