# Generated by Django 2.2.13 on 2020-06-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0005_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='colour',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
