# Generated by Django 2.2.13 on 2020-06-25 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_app', '0006_item_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='colour',
            new_name='color',
        ),
    ]
